Gpio sample fixes
tmakatos/muser pull request #1
Opened 2020-05-13 08:31 UTC by atomass

I don't know if this is the right place where to _clean_ the uuid. The problem is that if the uuid arrives with hyphens in the function `open_sock` (https://github.com/tmakatos/muser/blob/vfio-over-socket/lib/libmuser.c#L161) `strtoul` will fail.

2020-05-13 08:36 UTC, ismaell commented on samples/gpio-pci-idio-16.c
> +        for (int i = 0; i < strlen(uuid); i++) {
you can use `strcspn` to delimit chunks without hypens, then move only those chunks instead of the whole string.

2020-07-08 08:25 UTC, tmakatos commented
I'm really sorry I missed this PR, for some reason notifications were disabled in my own repository!

2020-07-08 08:27 UTC, tmakatos approved these changes

2020-07-08 08:30 UTC, tmakatos requested changes
I'm not sure this patch is needed at all. `lm_ctx_create` doesn't check at all the contents of `uuid`, it can really be anything. I think we need to fix the error message, and possibly the name of the `uuid` memder in `lm_ctx_t` and `dev_info` so that it's not misleading (it must be a UUID when muser.ko is used but not in the vfio-over-socket case).

2020-07-20 15:11 UTC, tmakatos commented
Fixed by 8e8c5564e4095a7498ac061314c69d740d07ba05.

2020-07-20 15:11 UTC, closed without merging